{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hanko-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hanko-operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hanko-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  type: ClusterIP
{{- end }}
