{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hanko-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hanko-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hanko-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
{{- end }}
