apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hanko-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hanko-operator.labels" . | nindent 4 }}
