package controller

import (
	"context"
	cryptorand "crypto/rand"
	"fmt"
	"math/big"
	"net"
	"net/url"
	"strings"
	"time"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/predicate"

	hankoshv1alpha1 "github.com/Alien6-Studio/hankoshell-operator/api/v1alpha1"
	"github.com/Alien6-Studio/hankoshell-operator/internal/adoption"
	"github.com/Alien6-Studio/hankoshell-operator/internal/keycloak"
)

const (
	requeueInterval = 30 * time.Second
	requeueOnError  = 10 * time.Second
	// Reconcile promptly after a persisted checkpoint without the deprecated Requeue flag.
	requeueImmediately = time.Millisecond
	requeueJitter      = 5 * time.Second
)

const (
	// ModeManage grants the operator full write authority over the Keycloak client:
	// create, update, delete, and secret management.
	ModeManage = "Manage"
	// ModeObserve restricts the operator to read-only status reporting: no create,
	// update, delete, or secret retrieval against Keycloak.
	ModeObserve = "Observe"

	// importedByLabel marks HankoApplication objects generated by HankoImport.
	// Present for backward compatibility with objects created before the Mode field
	// existed — such objects must always be treated as Observe.
	importedByLabel = "hanko.sh/imported-by"

	// realmClientIndexKey indexes HankoApplication objects by their (realmRef, clientID)
	// pair, so both HankoImport (dedup on import) and HankoApplication (conflict
	// detection between two Manage objects) can look up existing governors of a
	// given Keycloak client without listing and filtering the whole namespace.
	realmClientIndexKey = "spec.realmClient"

	// reconcileRequestAnnotation is an explicit, metadata-only reconcile nonce.
	// Deployment scripts use it when an applied spec is unchanged but provider
	// state still needs to be freshly verified.
	reconcileRequestAnnotation = "hanko.sh/reconcile-request"
)

func generationOrReconcileRequestChanged() predicate.Predicate {
	return predicate.Or(
		predicate.GenerationChangedPredicate{},
		predicate.Funcs{UpdateFunc: func(update event.UpdateEvent) bool {
			if update.ObjectOld == nil || update.ObjectNew == nil {
				return false
			}
			for _, key := range []string{reconcileRequestAnnotation, adoption.SourceAnnotation, adoption.ContractAnnotation, adoption.CandidateAnnotation, "hanko.sh/migrate-keycloak-client-uuid", "hanko.sh/migrate-keycloak-observation"} {
				oldValue, oldPresent := update.ObjectOld.GetAnnotations()[key]
				newValue, newPresent := update.ObjectNew.GetAnnotations()[key]
				if oldValue != newValue || oldPresent != newPresent {
					return true
				}
			}
			return update.ObjectOld.GetLabels()[importedByLabel] != update.ObjectNew.GetLabels()[importedByLabel] || update.ObjectOld.GetLabels()["hanko.sh/tenant"] != update.ObjectNew.GetLabels()["hanko.sh/tenant"] || !update.ObjectOld.GetDeletionTimestamp().Equal(update.ObjectNew.GetDeletionTimestamp())
		}},
	)
}

// realmClientKey builds the composite lookup key for a (realmRef, clientID) pair.
func realmClientKey(realmRef, clientID string) string {
	return realmRef + "/" + clientID
}

// isImported reports whether an object was discovered by HankoImport. Imported
// resources describe pre-existing Keycloak state and must never grant write or
// secret-management authority to the operator.
func isImported(labels map[string]string) bool {
	return labels[importedByLabel] != ""
}

// effectiveMode returns the operator's write authority over app's Keycloak client.
// An imported-by label always forces Observe, overriding spec.Mode, so that objects
// created before this field existed keep their original observe-only semantics.
func effectiveMode(app *hankoshv1alpha1.HankoApplication) string {
	if isImported(app.Labels) {
		return ModeObserve
	}
	if app.Spec.Mode == ModeObserve {
		return ModeObserve
	}
	return ModeManage
}

func effectiveRoleMode(role *hankoshv1alpha1.HankoRole) string {
	if isImported(role.Labels) || role.Spec.Mode == ModeObserve {
		return ModeObserve
	}
	return ModeManage
}
func effectiveServiceAccountMode(account *hankoshv1alpha1.HankoServiceAccount) string {
	if isImported(account.Labels) || account.Spec.Mode == ModeObserve {
		return ModeObserve
	}
	return ModeManage
}

func effectiveOrganizationMode(org *hankoshv1alpha1.HankoOrganization) string {
	if isImported(org.Labels) || org.Spec.Mode == ModeObserve {
		return ModeObserve
	}
	return ModeManage
}

// clientOwnershipCandidate identifies one Kubernetes object that can mutate a
// Keycloak client. Ownership is ordered by creation time so adding a colliding
// object can never displace the incumbent. UID, kind and name provide a stable
// tie-breaker for restored objects and fake-client tests whose timestamps may
// be identical.
type clientOwnershipCandidate struct {
	kind      string
	name      string
	uid       types.UID
	createdAt metav1.Time
}

func newClientOwnershipCandidate(kind string, obj metav1.Object) clientOwnershipCandidate {
	return clientOwnershipCandidate{
		kind:      kind,
		name:      obj.GetName(),
		uid:       obj.GetUID(),
		createdAt: obj.GetCreationTimestamp(),
	}
}

func clientOwnershipWinner(candidates []clientOwnershipCandidate) clientOwnershipCandidate {
	winner := candidates[0]
	for i := 1; i < len(candidates); i++ {
		if clientOwnershipPrecedes(candidates[i], winner) {
			winner = candidates[i]
		}
	}
	return winner
}

func clientOwnershipPrecedes(left, right clientOwnershipCandidate) bool {
	if !left.createdAt.Equal(&right.createdAt) {
		return left.createdAt.Before(&right.createdAt)
	}
	if left.uid != right.uid {
		return string(left.uid) < string(right.uid)
	}
	if left.kind != right.kind {
		return left.kind < right.kind
	}
	return left.name < right.name
}

func sameClientIdentity(leftRealm, leftClientID, rightRealm, rightClientID string) bool {
	return leftRealm == rightRealm && strings.TrimSpace(leftClientID) == strings.TrimSpace(rightClientID)
}

func isProtectedControlPlaneClient(protectedRealm string, protectedClientIDs []string, realmRef, clientID string) bool {
	protectedRealm = strings.TrimSpace(protectedRealm)
	if protectedRealm == "" || realmRef != protectedRealm {
		return false
	}
	clientID = strings.TrimSpace(clientID)
	for _, protectedClientID := range protectedClientIDs {
		if normalized := strings.TrimSpace(protectedClientID); normalized != "" && clientID == normalized {
			return true
		}
	}
	return false
}

// requeueWithJitter spreads reconciler load by adding up to requeueJitter of
// random delay on top of the base interval, preventing thundering-herd bursts
// when many objects share the same reconcile cadence.
func requeueWithJitter() time.Duration {
	jitter, err := cryptorand.Int(cryptorand.Reader, big.NewInt(int64(requeueJitter)))
	if err != nil {
		// Entropy failure must not prevent reconciliation. Omitting jitter is a
		// safe degradation: it changes scheduling only, never authorization.
		return requeueInterval
	}
	return requeueInterval + time.Duration(jitter.Int64())
}

// setCondition upserts a condition on a conditions slice.
// LastTransitionTime is updated only when Status changes, matching the K8s convention.
func setCondition(conditions *[]metav1.Condition, condType string, status metav1.ConditionStatus, reason, message string) {
	now := metav1.Now()
	for i, c := range *conditions {
		if c.Type == condType {
			if c.Status != status {
				(*conditions)[i].LastTransitionTime = now
			}
			(*conditions)[i].Status = status
			(*conditions)[i].Reason = reason
			(*conditions)[i].Message = message
			return
		}
	}
	*conditions = append(*conditions, metav1.Condition{
		Type:               condType,
		Status:             status,
		Reason:             reason,
		Message:            message,
		LastTransitionTime: now,
	})
}

// oidcEndpoints builds the standard OIDC endpoint URLs for a realm.
func oidcEndpoints(kc *keycloak.Client, realm string) *hankoshv1alpha1.OIDCEndpoints {
	base := fmt.Sprintf("%s/realms/%s/protocol/openid-connect", kc.BaseURL(), realm)
	issuer := fmt.Sprintf("%s/realms/%s", kc.BaseURL(), realm)
	return &hankoshv1alpha1.OIDCEndpoints{
		Issuer:        issuer,
		Authorization: base + "/auth",
		Token:         base + "/token",
		JWKS:          base + "/certs",
		UserInfo:      base + "/userinfo",
	}
}

// kcForObject returns the Keycloak client from the pool for the given object.
// Objects labelled with hanko.sh/tenant get the tenant's dedicated client;
// unlabelled objects fall back to the pool's default client.
func kcForObject(pool *keycloak.Pool, namespace string, labels map[string]string) *keycloak.Client {
	if pool == nil {
		return nil
	}
	tenantName := labels["hanko.sh/tenant"]
	return pool.Get(namespace + "/" + tenantName)
}

// validateKeycloakURL enforces ADR-022: Keycloak URL must use http/https and
// must not target cloud metadata endpoints.
func validateKeycloakURL(rawURL string) error {
	if err := keycloak.ValidateEndpoint(rawURL, true); err != nil {
		return err
	}
	u, err := url.Parse(rawURL)
	if err != nil {
		return fmt.Errorf("invalid Keycloak URL %q: %w", rawURL, err)
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return fmt.Errorf("keycloak URL %q must use http or https scheme (ADR-022)", rawURL)
	}
	host := u.Hostname()
	// Block cloud instance metadata endpoints (ADR-022).
	ip := net.ParseIP(host)
	for _, blocked := range metadataEndpointIPs() {
		if ip != nil && ip.Equal(blocked) {
			return fmt.Errorf("keycloak URL %q targets a blocked metadata endpoint (ADR-022)", rawURL)
		}
	}
	return nil
}

func metadataEndpointIPs() []net.IP {
	return []net.IP{
		net.IPv4(169, 254, 169, 254),
		{0xfd, 0x00, 0x0e, 0xc2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x54},
		net.IPv4(100, 100, 100, 200),
	}
}

// buildKCClientForInstance reads the AdminRef Secret from a HankoKeycloakInstance
// and returns a keycloak.Client. URL is validated (ADR-022). TLSCARef is honoured when set.
func buildKCClientForInstance(ctx context.Context, c client.Reader, ki *hankoshv1alpha1.HankoKeycloakInstance, requireHTTPS bool) (*keycloak.Client, error) {
	var secret corev1.Secret
	if err := c.Get(ctx, types.NamespacedName{Name: ki.Spec.AdminRef.Name, Namespace: ki.Namespace}, &secret); err != nil {
		return nil, fmt.Errorf("get admin secret %q: %w", ki.Spec.AdminRef.Name, err)
	}
	return buildKCClientFromAdminSecret(ctx, c, ki, &secret, "HANKO_KC_CLIENT_SECRET", requireHTTPS)
}

func buildKCClientFromAdminSecret(ctx context.Context, c client.Reader, ki *hankoshv1alpha1.HankoKeycloakInstance, secret *corev1.Secret, credentialKey string, requireHTTPS bool) (*keycloak.Client, error) {
	baseURL := string(secret.Data["HANKO_KEYCLOAK_URL"])
	clientID := string(secret.Data["HANKO_KC_CLIENT_ID"])
	clientSecret := string(secret.Data[credentialKey])
	if baseURL == "" || clientID == "" || clientSecret == "" {
		return nil, fmt.Errorf("secret %q missing HANKO_KEYCLOAK_URL / HANKO_KC_CLIENT_ID / %s", ki.Spec.AdminRef.Name, credentialKey)
	}
	if err := validateKeycloakURL(baseURL); err != nil {
		return nil, err
	}
	var kc *keycloak.Client
	if ki.Spec.TLSCARef != "" {
		var caSecret corev1.Secret
		if err := c.Get(ctx, types.NamespacedName{Name: ki.Spec.TLSCARef, Namespace: ki.Namespace}, &caSecret); err != nil {
			return nil, fmt.Errorf("get TLS CA secret %q: %w", ki.Spec.TLSCARef, err)
		}
		caPEM, ok := caSecret.Data["ca.crt"]
		if !ok || len(caPEM) == 0 {
			return nil, fmt.Errorf("TLS CA secret %q missing or empty \"ca.crt\" key", ki.Spec.TLSCARef)
		}
		var err error
		kc, err = keycloak.NewForOperator(baseURL, clientID, clientSecret, caPEM)
		if err != nil {
			return nil, err
		}
	} else {
		var err error
		kc, err = keycloak.NewForOperator(baseURL, clientID, clientSecret, nil)
		if err != nil {
			return nil, err
		}
	}
	if requireHTTPS {
		if err := kc.RequireHTTPS(); err != nil {
			return nil, err
		}
	}
	return kc, nil
}

// importResourceName produces a valid Kubernetes resource name from a realm ID and
// client ID. Characters outside [a-z0-9-] are replaced with hyphens and the result
// is capped at 63 characters with leading/trailing hyphens trimmed.
func importResourceName(realmID, clientID string) string {
	raw := strings.ToLower(realmID + "--" + clientID)
	var b strings.Builder
	for _, r := range raw {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			b.WriteRune(r)
		} else {
			b.WriteRune('-')
		}
	}
	name := b.String()
	if len(name) > 63 {
		name = name[:63]
	}
	return strings.Trim(name, "-")
}
