package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=hep,categories=hanko
// +kubebuilder:printcolumn:name="Type",type=string,JSONPath=".spec.type"
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=".status.phase"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=".metadata.creationTimestamp"

// HankoEmailProvider is a deprecated platform email configuration resource.
// Provider configuration and explicit tests now belong to the hankoShell API.
// Secret material is referenced by name and is never stored in this resource.
type HankoEmailProvider struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   HankoEmailProviderSpec   `json:"spec,omitempty"`
	Status HankoEmailProviderStatus `json:"status,omitempty"`
}

// HankoEmailProviderSpec defines the desired email provider configuration.
type HankoEmailProviderSpec struct {
	// Type selects the delivery adapter.
	// +kubebuilder:validation:Enum=office365
	Type string `json:"type"`

	// Enabled permits hankoShell platform services to use this provider.
	Enabled bool `json:"enabled"`

	// FromAddress is the default sender address.
	// +kubebuilder:validation:Format=email
	// +kubebuilder:validation:MaxLength=254
	FromAddress string `json:"fromAddress"`

	// FromName is the default sender display name.
	// +kubebuilder:validation:MaxLength=128
	// +kubebuilder:validation:Pattern=`^[^\r\n]*$`
	FromName string `json:"fromName,omitempty"`

	// Office365 contains Microsoft Graph application settings.
	Office365 *Office365EmailProviderSpec `json:"office365,omitempty"`

	// TestNonce requests a fresh delivery preflight when changed. It contains no
	// credentials and may safely be generated by the dashboard.
	// +kubebuilder:validation:MaxLength=128
	TestNonce string `json:"testNonce,omitempty"`
}

// Office365EmailProviderSpec contains non-secret Microsoft 365 settings.
type Office365EmailProviderSpec struct {
	// TenantID is the Microsoft Entra tenant UUID.
	// +kubebuilder:validation:Pattern=`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`
	TenantID string `json:"tenantID"`

	// ClientID is the Entra application UUID granted the Exchange Online
	// Application Mail.Send role scoped to Mailbox.
	// +kubebuilder:validation:Pattern=`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`
	ClientID string `json:"clientID"`

	// Mailbox is the Microsoft 365 mailbox targeted by Graph sendMail.
	// +kubebuilder:validation:Format=email
	// +kubebuilder:validation:MaxLength=254
	Mailbox string `json:"mailbox"`

	// KeyVaultSecretName is the Azure Key Vault secret containing the Entra
	// client secret. Retained only for migration; the operator no longer reads it.
	// +kubebuilder:validation:Pattern=`^[0-9A-Za-z-]{1,127}$`
	KeyVaultSecretName string `json:"keyVaultSecretName"`

	// PreflightRecipient receives the delivery preflight message. This proves
	// Graph token acquisition, Mail.Send authorisation and API acceptance before
	// hankoShell platform services can use the provider.
	// +kubebuilder:validation:Format=email
	// +kubebuilder:validation:MaxLength=254
	PreflightRecipient string `json:"preflightRecipient"`
}

// HankoEmailProviderStatus describes provider validation and delivery state.
type HankoEmailProviderStatus struct {
	// Phase summarises reconciliation state.
	// +kubebuilder:validation:Enum=Pending;Testing;Ready;Error;Disabled;Deprecated
	Phase string `json:"phase,omitempty"`

	// ObservedGeneration is the provider generation represented by this status.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// LastPreflight is legacy evidence, cleared when messaging is delegated to the API.
	LastPreflight *metav1.Time `json:"lastPreflight,omitempty"`

	// CredentialVersion is the non-secret Azure Key Vault version that passed
	// the recorded preflight. Hanko UI must not route through a newly rotated
	// version until that version has independently passed the same delivery test.
	CredentialVersion string `json:"credentialVersion,omitempty"`

	// Conditions holds standard Kubernetes condition objects.
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true

// HankoEmailProviderList contains a list of HankoEmailProvider resources.
type HankoEmailProviderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []HankoEmailProvider `json:"items"`
}

func init() {
	SchemeBuilder.Register(&HankoEmailProvider{}, &HankoEmailProviderList{})
}
