//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdoptedKeycloakSpec) DeepCopyInto(out *AdoptedKeycloakSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdoptedKeycloakSpec.
func (in *AdoptedKeycloakSpec) DeepCopy() *AdoptedKeycloakSpec {
	if in == nil {
		return nil
	}
	out := new(AdoptedKeycloakSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCapabilitySnapshot) DeepCopyInto(out *ApplicationCapabilitySnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCapabilitySnapshot.
func (in *ApplicationCapabilitySnapshot) DeepCopy() *ApplicationCapabilitySnapshot {
	if in == nil {
		return nil
	}
	out := new(ApplicationCapabilitySnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationIdentityMapping) DeepCopyInto(out *ApplicationIdentityMapping) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationIdentityMapping.
func (in *ApplicationIdentityMapping) DeepCopy() *ApplicationIdentityMapping {
	if in == nil {
		return nil
	}
	out := new(ApplicationIdentityMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationIdentityMappingTarget) DeepCopyInto(out *ApplicationIdentityMappingTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationIdentityMappingTarget.
func (in *ApplicationIdentityMappingTarget) DeepCopy() *ApplicationIdentityMappingTarget {
	if in == nil {
		return nil
	}
	out := new(ApplicationIdentityMappingTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationRole) DeepCopyInto(out *ApplicationRole) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationRole.
func (in *ApplicationRole) DeepCopy() *ApplicationRole {
	if in == nil {
		return nil
	}
	out := new(ApplicationRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationRuntimeBinding) DeepCopyInto(out *ApplicationRuntimeBinding) {
	*out = *in
	out.Workload = in.Workload
	out.PublicMetadata = in.PublicMetadata
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(ApplicationRuntimeCredentialTarget)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationRuntimeBinding.
func (in *ApplicationRuntimeBinding) DeepCopy() *ApplicationRuntimeBinding {
	if in == nil {
		return nil
	}
	out := new(ApplicationRuntimeBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationRuntimeBindingStatus) DeepCopyInto(out *ApplicationRuntimeBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationRuntimeBindingStatus.
func (in *ApplicationRuntimeBindingStatus) DeepCopy() *ApplicationRuntimeBindingStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationRuntimeBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationRuntimeCredentialTarget) DeepCopyInto(out *ApplicationRuntimeCredentialTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationRuntimeCredentialTarget.
func (in *ApplicationRuntimeCredentialTarget) DeepCopy() *ApplicationRuntimeCredentialTarget {
	if in == nil {
		return nil
	}
	out := new(ApplicationRuntimeCredentialTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationRuntimeMetadataTarget) DeepCopyInto(out *ApplicationRuntimeMetadataTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationRuntimeMetadataTarget.
func (in *ApplicationRuntimeMetadataTarget) DeepCopy() *ApplicationRuntimeMetadataTarget {
	if in == nil {
		return nil
	}
	out := new(ApplicationRuntimeMetadataTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationRuntimeWorkload) DeepCopyInto(out *ApplicationRuntimeWorkload) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationRuntimeWorkload.
func (in *ApplicationRuntimeWorkload) DeepCopy() *ApplicationRuntimeWorkload {
	if in == nil {
		return nil
	}
	out := new(ApplicationRuntimeWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSAML) DeepCopyInto(out *ApplicationSAML) {
	*out = *in
	if in.AssertionConsumerServices != nil {
		in, out := &in.AssertionConsumerServices, &out.AssertionConsumerServices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequireSignedAssertions != nil {
		in, out := &in.RequireSignedAssertions, &out.RequireSignedAssertions
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSAML.
func (in *ApplicationSAML) DeepCopy() *ApplicationSAML {
	if in == nil {
		return nil
	}
	out := new(ApplicationSAML)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSecretProjection) DeepCopyInto(out *ApplicationSecretProjection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSecretProjection.
func (in *ApplicationSecretProjection) DeepCopy() *ApplicationSecretProjection {
	if in == nil {
		return nil
	}
	out := new(ApplicationSecretProjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationTokenClaim) DeepCopyInto(out *ApplicationTokenClaim) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.AddToIDToken != nil {
		in, out := &in.AddToIDToken, &out.AddToIDToken
		*out = new(bool)
		**out = **in
	}
	if in.AddToAccessToken != nil {
		in, out := &in.AddToAccessToken, &out.AddToAccessToken
		*out = new(bool)
		**out = **in
	}
	if in.AddToUserInfo != nil {
		in, out := &in.AddToUserInfo, &out.AddToUserInfo
		*out = new(bool)
		**out = **in
	}
	if in.AddToIntrospection != nil {
		in, out := &in.AddToIntrospection, &out.AddToIntrospection
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationTokenClaim.
func (in *ApplicationTokenClaim) DeepCopy() *ApplicationTokenClaim {
	if in == nil {
		return nil
	}
	out := new(ApplicationTokenClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationCapabilitySnapshot) DeepCopyInto(out *AuthorizationCapabilitySnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationCapabilitySnapshot.
func (in *AuthorizationCapabilitySnapshot) DeepCopy() *AuthorizationCapabilitySnapshot {
	if in == nil {
		return nil
	}
	out := new(AuthorizationCapabilitySnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationFinding) DeepCopyInto(out *AuthorizationFinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationFinding.
func (in *AuthorizationFinding) DeepCopy() *AuthorizationFinding {
	if in == nil {
		return nil
	}
	out := new(AuthorizationFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationManagedObjects) DeepCopyInto(out *AuthorizationManagedObjects) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]AuthorizationManagedReference, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]AuthorizationManagedReference, len(*in))
		copy(*out, *in)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]AuthorizationManagedReference, len(*in))
		copy(*out, *in)
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]AuthorizationManagedReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationManagedObjects.
func (in *AuthorizationManagedObjects) DeepCopy() *AuthorizationManagedObjects {
	if in == nil {
		return nil
	}
	out := new(AuthorizationManagedObjects)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationManagedReference) DeepCopyInto(out *AuthorizationManagedReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationManagedReference.
func (in *AuthorizationManagedReference) DeepCopy() *AuthorizationManagedReference {
	if in == nil {
		return nil
	}
	out := new(AuthorizationManagedReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationPermission) DeepCopyInto(out *AuthorizationPermission) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Principals != nil {
		in, out := &in.Principals, &out.Principals
		*out = make([]AuthorizationPrincipal, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationPermission.
func (in *AuthorizationPermission) DeepCopy() *AuthorizationPermission {
	if in == nil {
		return nil
	}
	out := new(AuthorizationPermission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationPrincipal) DeepCopyInto(out *AuthorizationPrincipal) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationPrincipal.
func (in *AuthorizationPrincipal) DeepCopy() *AuthorizationPrincipal {
	if in == nil {
		return nil
	}
	out := new(AuthorizationPrincipal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationResource) DeepCopyInto(out *AuthorizationResource) {
	*out = *in
	if in.URIs != nil {
		in, out := &in.URIs, &out.URIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationResource.
func (in *AuthorizationResource) DeepCopy() *AuthorizationResource {
	if in == nil {
		return nil
	}
	out := new(AuthorizationResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationScope) DeepCopyInto(out *AuthorizationScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationScope.
func (in *AuthorizationScope) DeepCopy() *AuthorizationScope {
	if in == nil {
		return nil
	}
	out := new(AuthorizationScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BruteForcePolicy) DeepCopyInto(out *BruteForcePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BruteForcePolicy.
func (in *BruteForcePolicy) DeepCopy() *BruteForcePolicy {
	if in == nil {
		return nil
	}
	out := new(BruteForcePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloneSpec) DeepCopyInto(out *CloneSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloneSpec.
func (in *CloneSpec) DeepCopy() *CloneSpec {
	if in == nil {
		return nil
	}
	out := new(CloneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBSwitchSpec) DeepCopyInto(out *DBSwitchSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBSwitchSpec.
func (in *DBSwitchSpec) DeepCopy() *DBSwitchSpec {
	if in == nil {
		return nil
	}
	out := new(DBSwitchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoApplication) DeepCopyInto(out *HankoApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoApplication.
func (in *HankoApplication) DeepCopy() *HankoApplication {
	if in == nil {
		return nil
	}
	out := new(HankoApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoApplicationList) DeepCopyInto(out *HankoApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoApplicationList.
func (in *HankoApplicationList) DeepCopy() *HankoApplicationList {
	if in == nil {
		return nil
	}
	out := new(HankoApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoApplicationSpec) DeepCopyInto(out *HankoApplicationSpec) {
	*out = *in
	if in.SAML != nil {
		in, out := &in.SAML, &out.SAML
		*out = new(ApplicationSAML)
		(*in).DeepCopyInto(*out)
	}
	if in.RedirectURIs != nil {
		in, out := &in.RedirectURIs, &out.RedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostLogoutRedirectURIs != nil {
		in, out := &in.PostLogoutRedirectURIs, &out.PostLogoutRedirectURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]ApplicationRole, len(*in))
		copy(*out, *in)
	}
	if in.RealmRoleScopes != nil {
		in, out := &in.RealmRoleScopes, &out.RealmRoleScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IdentityMappings != nil {
		in, out := &in.IdentityMappings, &out.IdentityMappings
		*out = make([]ApplicationIdentityMapping, len(*in))
		copy(*out, *in)
	}
	if in.TokenClaims != nil {
		in, out := &in.TokenClaims, &out.TokenClaims
		*out = make([]ApplicationTokenClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecretRotationPolicy != nil {
		in, out := &in.SecretRotationPolicy, &out.SecretRotationPolicy
		*out = new(SecretRotationPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientSecretProjections != nil {
		in, out := &in.ClientSecretProjections, &out.ClientSecretProjections
		*out = make([]ApplicationSecretProjection, len(*in))
		copy(*out, *in)
	}
	if in.RuntimeBindings != nil {
		in, out := &in.RuntimeBindings, &out.RuntimeBindings
		*out = make([]ApplicationRuntimeBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoApplicationSpec.
func (in *HankoApplicationSpec) DeepCopy() *HankoApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(HankoApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoApplicationStatus) DeepCopyInto(out *HankoApplicationStatus) {
	*out = *in
	if in.RuntimeBindings != nil {
		in, out := &in.RuntimeBindings, &out.RuntimeBindings
		*out = make([]ApplicationRuntimeBindingStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.CapabilityEvidence = in.CapabilityEvidence
	out.Capabilities = in.Capabilities
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]AuthorizationFinding, len(*in))
		copy(*out, *in)
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.OIDCEndpoints != nil {
		in, out := &in.OIDCEndpoints, &out.OIDCEndpoints
		*out = new(OIDCEndpoints)
		**out = **in
	}
	if in.SAMLEndpoints != nil {
		in, out := &in.SAMLEndpoints, &out.SAMLEndpoints
		*out = new(SAMLEndpoints)
		**out = **in
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.LastRotated != nil {
		in, out := &in.LastRotated, &out.LastRotated
		*out = (*in).DeepCopy()
	}
	if in.NextRotation != nil {
		in, out := &in.NextRotation, &out.NextRotation
		*out = (*in).DeepCopy()
	}
	if in.ManagedClientSecretProjections != nil {
		in, out := &in.ManagedClientSecretProjections, &out.ManagedClientSecretProjections
		*out = make([]ApplicationSecretProjection, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedIdentityMappings != nil {
		in, out := &in.ManagedIdentityMappings, &out.ManagedIdentityMappings
		*out = make([]ManagedIdentityMappingReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedTokenClaims != nil {
		in, out := &in.ManagedTokenClaims, &out.ManagedTokenClaims
		*out = make([]ManagedTokenClaimReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoApplicationStatus.
func (in *HankoApplicationStatus) DeepCopy() *HankoApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(HankoApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoEmailProvider) DeepCopyInto(out *HankoEmailProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoEmailProvider.
func (in *HankoEmailProvider) DeepCopy() *HankoEmailProvider {
	if in == nil {
		return nil
	}
	out := new(HankoEmailProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoEmailProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoEmailProviderList) DeepCopyInto(out *HankoEmailProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoEmailProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoEmailProviderList.
func (in *HankoEmailProviderList) DeepCopy() *HankoEmailProviderList {
	if in == nil {
		return nil
	}
	out := new(HankoEmailProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoEmailProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoEmailProviderSpec) DeepCopyInto(out *HankoEmailProviderSpec) {
	*out = *in
	if in.Office365 != nil {
		in, out := &in.Office365, &out.Office365
		*out = new(Office365EmailProviderSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoEmailProviderSpec.
func (in *HankoEmailProviderSpec) DeepCopy() *HankoEmailProviderSpec {
	if in == nil {
		return nil
	}
	out := new(HankoEmailProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoEmailProviderStatus) DeepCopyInto(out *HankoEmailProviderStatus) {
	*out = *in
	if in.LastPreflight != nil {
		in, out := &in.LastPreflight, &out.LastPreflight
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoEmailProviderStatus.
func (in *HankoEmailProviderStatus) DeepCopy() *HankoEmailProviderStatus {
	if in == nil {
		return nil
	}
	out := new(HankoEmailProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoIAMProfile) DeepCopyInto(out *HankoIAMProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoIAMProfile.
func (in *HankoIAMProfile) DeepCopy() *HankoIAMProfile {
	if in == nil {
		return nil
	}
	out := new(HankoIAMProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoIAMProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoIAMProfileList) DeepCopyInto(out *HankoIAMProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoIAMProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoIAMProfileList.
func (in *HankoIAMProfileList) DeepCopy() *HankoIAMProfileList {
	if in == nil {
		return nil
	}
	out := new(HankoIAMProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoIAMProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoIAMProfileSpec) DeepCopyInto(out *HankoIAMProfileSpec) {
	*out = *in
	in.Security.DeepCopyInto(&out.Security)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoIAMProfileSpec.
func (in *HankoIAMProfileSpec) DeepCopy() *HankoIAMProfileSpec {
	if in == nil {
		return nil
	}
	out := new(HankoIAMProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoIAMProfileStatus) DeepCopyInto(out *HankoIAMProfileStatus) {
	*out = *in
	if in.LastValidated != nil {
		in, out := &in.LastValidated, &out.LastValidated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoIAMProfileStatus.
func (in *HankoIAMProfileStatus) DeepCopy() *HankoIAMProfileStatus {
	if in == nil {
		return nil
	}
	out := new(HankoIAMProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoImport) DeepCopyInto(out *HankoImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoImport.
func (in *HankoImport) DeepCopy() *HankoImport {
	if in == nil {
		return nil
	}
	out := new(HankoImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoImportList) DeepCopyInto(out *HankoImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoImportList.
func (in *HankoImportList) DeepCopy() *HankoImportList {
	if in == nil {
		return nil
	}
	out := new(HankoImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoImportSpec) DeepCopyInto(out *HankoImportSpec) {
	*out = *in
	if in.Realms != nil {
		in, out := &in.Realms, &out.Realms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeClients != nil {
		in, out := &in.IncludeClients, &out.IncludeClients
		*out = new(bool)
		**out = **in
	}
	if in.IncludeServiceAccounts != nil {
		in, out := &in.IncludeServiceAccounts, &out.IncludeServiceAccounts
		*out = new(bool)
		**out = **in
	}
	if in.IncludeIdentityProviders != nil {
		in, out := &in.IncludeIdentityProviders, &out.IncludeIdentityProviders
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoImportSpec.
func (in *HankoImportSpec) DeepCopy() *HankoImportSpec {
	if in == nil {
		return nil
	}
	out := new(HankoImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoImportStatus) DeepCopyInto(out *HankoImportStatus) {
	*out = *in
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]AuthorizationFinding, len(*in))
		copy(*out, *in)
	}
	out.Discovered = in.Discovered
	out.Applied = in.Applied
	out.Skipped = in.Skipped
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoImportStatus.
func (in *HankoImportStatus) DeepCopy() *HankoImportStatus {
	if in == nil {
		return nil
	}
	out := new(HankoImportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoIssuer) DeepCopyInto(out *HankoIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoIssuer.
func (in *HankoIssuer) DeepCopy() *HankoIssuer {
	if in == nil {
		return nil
	}
	out := new(HankoIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoIssuerList) DeepCopyInto(out *HankoIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoIssuerList.
func (in *HankoIssuerList) DeepCopy() *HankoIssuerList {
	if in == nil {
		return nil
	}
	out := new(HankoIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoIssuerSpec) DeepCopyInto(out *HankoIssuerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoIssuerSpec.
func (in *HankoIssuerSpec) DeepCopy() *HankoIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(HankoIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoIssuerStatus) DeepCopyInto(out *HankoIssuerStatus) {
	*out = *in
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoIssuerStatus.
func (in *HankoIssuerStatus) DeepCopy() *HankoIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(HankoIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoKeycloakInstance) DeepCopyInto(out *HankoKeycloakInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoKeycloakInstance.
func (in *HankoKeycloakInstance) DeepCopy() *HankoKeycloakInstance {
	if in == nil {
		return nil
	}
	out := new(HankoKeycloakInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoKeycloakInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoKeycloakInstanceList) DeepCopyInto(out *HankoKeycloakInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoKeycloakInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoKeycloakInstanceList.
func (in *HankoKeycloakInstanceList) DeepCopy() *HankoKeycloakInstanceList {
	if in == nil {
		return nil
	}
	out := new(HankoKeycloakInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoKeycloakInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoKeycloakInstanceSpec) DeepCopyInto(out *HankoKeycloakInstanceSpec) {
	*out = *in
	out.AdminRef = in.AdminRef
	if in.Managed != nil {
		in, out := &in.Managed, &out.Managed
		*out = new(ManagedKeycloakSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Adopted != nil {
		in, out := &in.Adopted, &out.Adopted
		*out = new(AdoptedKeycloakSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoKeycloakInstanceSpec.
func (in *HankoKeycloakInstanceSpec) DeepCopy() *HankoKeycloakInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(HankoKeycloakInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoKeycloakInstanceStatus) DeepCopyInto(out *HankoKeycloakInstanceStatus) {
	*out = *in
	if in.LastProbed != nil {
		in, out := &in.LastProbed, &out.LastProbed
		*out = (*in).DeepCopy()
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.LastCredentialRotation != nil {
		in, out := &in.LastCredentialRotation, &out.LastCredentialRotation
		*out = (*in).DeepCopy()
	}
	if in.NextCredentialRotation != nil {
		in, out := &in.NextCredentialRotation, &out.NextCredentialRotation
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoKeycloakInstanceStatus.
func (in *HankoKeycloakInstanceStatus) DeepCopy() *HankoKeycloakInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(HankoKeycloakInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoMeshService) DeepCopyInto(out *HankoMeshService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoMeshService.
func (in *HankoMeshService) DeepCopy() *HankoMeshService {
	if in == nil {
		return nil
	}
	out := new(HankoMeshService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoMeshService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoMeshServiceList) DeepCopyInto(out *HankoMeshServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoMeshService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoMeshServiceList.
func (in *HankoMeshServiceList) DeepCopy() *HankoMeshServiceList {
	if in == nil {
		return nil
	}
	out := new(HankoMeshServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoMeshServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoMeshServiceSpec) DeepCopyInto(out *HankoMeshServiceSpec) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]MeshServicePort, len(*in))
		copy(*out, *in)
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]MeshServiceEgress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoMeshServiceSpec.
func (in *HankoMeshServiceSpec) DeepCopy() *HankoMeshServiceSpec {
	if in == nil {
		return nil
	}
	out := new(HankoMeshServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoMeshServiceStatus) DeepCopyInto(out *HankoMeshServiceStatus) {
	*out = *in
	if in.ReceiverNodeUIDs != nil {
		in, out := &in.ReceiverNodeUIDs, &out.ReceiverNodeUIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResolvedPorts != nil {
		in, out := &in.ResolvedPorts, &out.ResolvedPorts
		*out = make([]MeshServicePort, len(*in))
		copy(*out, *in)
	}
	if in.ResolvedEgress != nil {
		in, out := &in.ResolvedEgress, &out.ResolvedEgress
		*out = make([]ResolvedMeshServiceEgress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastResolved != nil {
		in, out := &in.LastResolved, &out.LastResolved
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoMeshServiceStatus.
func (in *HankoMeshServiceStatus) DeepCopy() *HankoMeshServiceStatus {
	if in == nil {
		return nil
	}
	out := new(HankoMeshServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoOperation) DeepCopyInto(out *HankoOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoOperation.
func (in *HankoOperation) DeepCopy() *HankoOperation {
	if in == nil {
		return nil
	}
	out := new(HankoOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoOperationList) DeepCopyInto(out *HankoOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoOperationList.
func (in *HankoOperationList) DeepCopy() *HankoOperationList {
	if in == nil {
		return nil
	}
	out := new(HankoOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoOperationSpec) DeepCopyInto(out *HankoOperationSpec) {
	*out = *in
	if in.SnapshotBefore != nil {
		in, out := &in.SnapshotBefore, &out.SnapshotBefore
		*out = new(bool)
		**out = **in
	}
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(UpgradeSpec)
		**out = **in
	}
	if in.Clone != nil {
		in, out := &in.Clone, &out.Clone
		*out = new(CloneSpec)
		**out = **in
	}
	if in.DBSwitch != nil {
		in, out := &in.DBSwitch, &out.DBSwitch
		*out = new(DBSwitchSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoOperationSpec.
func (in *HankoOperationSpec) DeepCopy() *HankoOperationSpec {
	if in == nil {
		return nil
	}
	out := new(HankoOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoOperationStatus) DeepCopyInto(out *HankoOperationStatus) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]OperationStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoOperationStatus.
func (in *HankoOperationStatus) DeepCopy() *HankoOperationStatus {
	if in == nil {
		return nil
	}
	out := new(HankoOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoOrganization) DeepCopyInto(out *HankoOrganization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoOrganization.
func (in *HankoOrganization) DeepCopy() *HankoOrganization {
	if in == nil {
		return nil
	}
	out := new(HankoOrganization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoOrganization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoOrganizationList) DeepCopyInto(out *HankoOrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoOrganization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoOrganizationList.
func (in *HankoOrganizationList) DeepCopy() *HankoOrganizationList {
	if in == nil {
		return nil
	}
	out := new(HankoOrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoOrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoOrganizationSpec) DeepCopyInto(out *HankoOrganizationSpec) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientRoles != nil {
		in, out := &in.ClientRoles, &out.ClientRoles
		*out = make([]OrganizationClientRoles, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoOrganizationSpec.
func (in *HankoOrganizationSpec) DeepCopy() *HankoOrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(HankoOrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoOrganizationStatus) DeepCopyInto(out *HankoOrganizationStatus) {
	*out = *in
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoOrganizationStatus.
func (in *HankoOrganizationStatus) DeepCopy() *HankoOrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(HankoOrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoRealm) DeepCopyInto(out *HankoRealm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoRealm.
func (in *HankoRealm) DeepCopy() *HankoRealm {
	if in == nil {
		return nil
	}
	out := new(HankoRealm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoRealm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoRealmList) DeepCopyInto(out *HankoRealmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoRealm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoRealmList.
func (in *HankoRealmList) DeepCopy() *HankoRealmList {
	if in == nil {
		return nil
	}
	out := new(HankoRealmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoRealmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoRealmSpec) DeepCopyInto(out *HankoRealmSpec) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]RealmRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IdentityProviders != nil {
		in, out := &in.IdentityProviders, &out.IdentityProviders
		*out = make([]RealmIdentityProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityProfile != nil {
		in, out := &in.SecurityProfile, &out.SecurityProfile
		*out = new(RealmSecurityProfile)
		(*in).DeepCopyInto(*out)
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(RealmEmailRouteSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoRealmSpec.
func (in *HankoRealmSpec) DeepCopy() *HankoRealmSpec {
	if in == nil {
		return nil
	}
	out := new(HankoRealmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoRealmStatus) DeepCopyInto(out *HankoRealmStatus) {
	*out = *in
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.ManagedIdentityProviders != nil {
		in, out := &in.ManagedIdentityProviders, &out.ManagedIdentityProviders
		*out = make([]ManagedRealmIdentityProviderReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoRealmStatus.
func (in *HankoRealmStatus) DeepCopy() *HankoRealmStatus {
	if in == nil {
		return nil
	}
	out := new(HankoRealmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoResourceServer) DeepCopyInto(out *HankoResourceServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoResourceServer.
func (in *HankoResourceServer) DeepCopy() *HankoResourceServer {
	if in == nil {
		return nil
	}
	out := new(HankoResourceServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoResourceServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoResourceServerList) DeepCopyInto(out *HankoResourceServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoResourceServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoResourceServerList.
func (in *HankoResourceServerList) DeepCopy() *HankoResourceServerList {
	if in == nil {
		return nil
	}
	out := new(HankoResourceServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoResourceServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoResourceServerSpec) DeepCopyInto(out *HankoResourceServerSpec) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]AuthorizationScope, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]AuthorizationResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]AuthorizationPermission, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoResourceServerSpec.
func (in *HankoResourceServerSpec) DeepCopy() *HankoResourceServerSpec {
	if in == nil {
		return nil
	}
	out := new(HankoResourceServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoResourceServerStatus) DeepCopyInto(out *HankoResourceServerStatus) {
	*out = *in
	out.CapabilityEvidence = in.CapabilityEvidence
	out.Capabilities = in.Capabilities
	in.ManagedObjects.DeepCopyInto(&out.ManagedObjects)
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]AuthorizationFinding, len(*in))
		copy(*out, *in)
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoResourceServerStatus.
func (in *HankoResourceServerStatus) DeepCopy() *HankoResourceServerStatus {
	if in == nil {
		return nil
	}
	out := new(HankoResourceServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoRole) DeepCopyInto(out *HankoRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoRole.
func (in *HankoRole) DeepCopy() *HankoRole {
	if in == nil {
		return nil
	}
	out := new(HankoRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoRoleList) DeepCopyInto(out *HankoRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoRoleList.
func (in *HankoRoleList) DeepCopy() *HankoRoleList {
	if in == nil {
		return nil
	}
	out := new(HankoRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoRoleSpec) DeepCopyInto(out *HankoRoleSpec) {
	*out = *in
	if in.Composites != nil {
		in, out := &in.Composites, &out.Composites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoRoleSpec.
func (in *HankoRoleSpec) DeepCopy() *HankoRoleSpec {
	if in == nil {
		return nil
	}
	out := new(HankoRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoRoleStatus) DeepCopyInto(out *HankoRoleStatus) {
	*out = *in
	out.CapabilityEvidence = in.CapabilityEvidence
	out.Capabilities = in.Capabilities
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]AuthorizationFinding, len(*in))
		copy(*out, *in)
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoRoleStatus.
func (in *HankoRoleStatus) DeepCopy() *HankoRoleStatus {
	if in == nil {
		return nil
	}
	out := new(HankoRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoServiceAccount) DeepCopyInto(out *HankoServiceAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoServiceAccount.
func (in *HankoServiceAccount) DeepCopy() *HankoServiceAccount {
	if in == nil {
		return nil
	}
	out := new(HankoServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoServiceAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoServiceAccountList) DeepCopyInto(out *HankoServiceAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoServiceAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoServiceAccountList.
func (in *HankoServiceAccountList) DeepCopy() *HankoServiceAccountList {
	if in == nil {
		return nil
	}
	out := new(HankoServiceAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoServiceAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoServiceAccountSpec) DeepCopyInto(out *HankoServiceAccountSpec) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecretRotationPolicy != nil {
		in, out := &in.SecretRotationPolicy, &out.SecretRotationPolicy
		*out = new(SecretRotationPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TokenClaims != nil {
		in, out := &in.TokenClaims, &out.TokenClaims
		*out = make([]ApplicationTokenClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoServiceAccountSpec.
func (in *HankoServiceAccountSpec) DeepCopy() *HankoServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(HankoServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoServiceAccountStatus) DeepCopyInto(out *HankoServiceAccountStatus) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.LastRotated != nil {
		in, out := &in.LastRotated, &out.LastRotated
		*out = (*in).DeepCopy()
	}
	if in.NextRotation != nil {
		in, out := &in.NextRotation, &out.NextRotation
		*out = (*in).DeepCopy()
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedTokenClaims != nil {
		in, out := &in.ManagedTokenClaims, &out.ManagedTokenClaims
		*out = make([]ManagedTokenClaimReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoServiceAccountStatus.
func (in *HankoServiceAccountStatus) DeepCopy() *HankoServiceAccountStatus {
	if in == nil {
		return nil
	}
	out := new(HankoServiceAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoSnapshot) DeepCopyInto(out *HankoSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoSnapshot.
func (in *HankoSnapshot) DeepCopy() *HankoSnapshot {
	if in == nil {
		return nil
	}
	out := new(HankoSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoSnapshotList) DeepCopyInto(out *HankoSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoSnapshotList.
func (in *HankoSnapshotList) DeepCopy() *HankoSnapshotList {
	if in == nil {
		return nil
	}
	out := new(HankoSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoSnapshotSpec) DeepCopyInto(out *HankoSnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoSnapshotSpec.
func (in *HankoSnapshotSpec) DeepCopy() *HankoSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(HankoSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoSnapshotStatus) DeepCopyInto(out *HankoSnapshotStatus) {
	*out = *in
	if in.TakenAt != nil {
		in, out := &in.TakenAt, &out.TakenAt
		*out = (*in).DeepCopy()
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoSnapshotStatus.
func (in *HankoSnapshotStatus) DeepCopy() *HankoSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(HankoSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoTenant) DeepCopyInto(out *HankoTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoTenant.
func (in *HankoTenant) DeepCopy() *HankoTenant {
	if in == nil {
		return nil
	}
	out := new(HankoTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoTenantList) DeepCopyInto(out *HankoTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoTenantList.
func (in *HankoTenantList) DeepCopy() *HankoTenantList {
	if in == nil {
		return nil
	}
	out := new(HankoTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoTenantSpec) DeepCopyInto(out *HankoTenantSpec) {
	*out = *in
	if in.KeycloakSecretRef != nil {
		in, out := &in.KeycloakSecretRef, &out.KeycloakSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	out.HubTokenSecretRef = in.HubTokenSecretRef
	if in.HubEnrollSecretRef != nil {
		in, out := &in.HubEnrollSecretRef, &out.HubEnrollSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoTenantSpec.
func (in *HankoTenantSpec) DeepCopy() *HankoTenantSpec {
	if in == nil {
		return nil
	}
	out := new(HankoTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoTenantStatus) DeepCopyInto(out *HankoTenantStatus) {
	*out = *in
	if in.LastSync != nil {
		in, out := &in.LastSync, &out.LastSync
		*out = (*in).DeepCopy()
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoTenantStatus.
func (in *HankoTenantStatus) DeepCopy() *HankoTenantStatus {
	if in == nil {
		return nil
	}
	out := new(HankoTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoTheme) DeepCopyInto(out *HankoTheme) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoTheme.
func (in *HankoTheme) DeepCopy() *HankoTheme {
	if in == nil {
		return nil
	}
	out := new(HankoTheme)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoTheme) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoThemeList) DeepCopyInto(out *HankoThemeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HankoTheme, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoThemeList.
func (in *HankoThemeList) DeepCopy() *HankoThemeList {
	if in == nil {
		return nil
	}
	out := new(HankoThemeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HankoThemeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoThemeSpec) DeepCopyInto(out *HankoThemeSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoThemeSpec.
func (in *HankoThemeSpec) DeepCopy() *HankoThemeSpec {
	if in == nil {
		return nil
	}
	out := new(HankoThemeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HankoThemeStatus) DeepCopyInto(out *HankoThemeStatus) {
	*out = *in
	if in.LastBuilt != nil {
		in, out := &in.LastBuilt, &out.LastBuilt
		*out = (*in).DeepCopy()
	}
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.InstalledImagePullSecrets != nil {
		in, out := &in.InstalledImagePullSecrets, &out.InstalledImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HankoThemeStatus.
func (in *HankoThemeStatus) DeepCopy() *HankoThemeStatus {
	if in == nil {
		return nil
	}
	out := new(HankoThemeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMCapabilityEvidence) DeepCopyInto(out *IAMCapabilityEvidence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMCapabilityEvidence.
func (in *IAMCapabilityEvidence) DeepCopy() *IAMCapabilityEvidence {
	if in == nil {
		return nil
	}
	out := new(IAMCapabilityEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportCounts) DeepCopyInto(out *ImportCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportCounts.
func (in *ImportCounts) DeepCopy() *ImportCounts {
	if in == nil {
		return nil
	}
	out := new(ImportCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedIdentityMappingReference) DeepCopyInto(out *ManagedIdentityMappingReference) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedIdentityMappingReference.
func (in *ManagedIdentityMappingReference) DeepCopy() *ManagedIdentityMappingReference {
	if in == nil {
		return nil
	}
	out := new(ManagedIdentityMappingReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedKeycloakSpec) DeepCopyInto(out *ManagedKeycloakSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.Database = in.Database
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedKeycloakSpec.
func (in *ManagedKeycloakSpec) DeepCopy() *ManagedKeycloakSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedKeycloakSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRealmIdentityProviderMapperReference) DeepCopyInto(out *ManagedRealmIdentityProviderMapperReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRealmIdentityProviderMapperReference.
func (in *ManagedRealmIdentityProviderMapperReference) DeepCopy() *ManagedRealmIdentityProviderMapperReference {
	if in == nil {
		return nil
	}
	out := new(ManagedRealmIdentityProviderMapperReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRealmIdentityProviderReference) DeepCopyInto(out *ManagedRealmIdentityProviderReference) {
	*out = *in
	if in.Mappers != nil {
		in, out := &in.Mappers, &out.Mappers
		*out = make([]ManagedRealmIdentityProviderMapperReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRealmIdentityProviderReference.
func (in *ManagedRealmIdentityProviderReference) DeepCopy() *ManagedRealmIdentityProviderReference {
	if in == nil {
		return nil
	}
	out := new(ManagedRealmIdentityProviderReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedTokenClaimReference) DeepCopyInto(out *ManagedTokenClaimReference) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedTokenClaimReference.
func (in *ManagedTokenClaimReference) DeepCopy() *ManagedTokenClaimReference {
	if in == nil {
		return nil
	}
	out := new(ManagedTokenClaimReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshServiceEgress) DeepCopyInto(out *MeshServiceEgress) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]MeshServicePort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshServiceEgress.
func (in *MeshServiceEgress) DeepCopy() *MeshServiceEgress {
	if in == nil {
		return nil
	}
	out := new(MeshServiceEgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshServicePort) DeepCopyInto(out *MeshServicePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshServicePort.
func (in *MeshServicePort) DeepCopy() *MeshServicePort {
	if in == nil {
		return nil
	}
	out := new(MeshServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCEndpoints) DeepCopyInto(out *OIDCEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCEndpoints.
func (in *OIDCEndpoints) DeepCopy() *OIDCEndpoints {
	if in == nil {
		return nil
	}
	out := new(OIDCEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Office365EmailProviderSpec) DeepCopyInto(out *Office365EmailProviderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Office365EmailProviderSpec.
func (in *Office365EmailProviderSpec) DeepCopy() *Office365EmailProviderSpec {
	if in == nil {
		return nil
	}
	out := new(Office365EmailProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationStep) DeepCopyInto(out *OperationStep) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationStep.
func (in *OperationStep) DeepCopy() *OperationStep {
	if in == nil {
		return nil
	}
	out := new(OperationStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationClientRoles) DeepCopyInto(out *OrganizationClientRoles) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationClientRoles.
func (in *OrganizationClientRoles) DeepCopy() *OrganizationClientRoles {
	if in == nil {
		return nil
	}
	out := new(OrganizationClientRoles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmEmailRouteSpec) DeepCopyInto(out *RealmEmailRouteSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmEmailRouteSpec.
func (in *RealmEmailRouteSpec) DeepCopy() *RealmEmailRouteSpec {
	if in == nil {
		return nil
	}
	out := new(RealmEmailRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmIdentityProvider) DeepCopyInto(out *RealmIdentityProvider) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.TrustEmail != nil {
		in, out := &in.TrustEmail, &out.TrustEmail
		*out = new(bool)
		**out = **in
	}
	if in.StoreToken != nil {
		in, out := &in.StoreToken, &out.StoreToken
		*out = new(bool)
		**out = **in
	}
	if in.AddReadTokenRoleOnCreate != nil {
		in, out := &in.AddReadTokenRoleOnCreate, &out.AddReadTokenRoleOnCreate
		*out = new(bool)
		**out = **in
	}
	if in.LinkOnly != nil {
		in, out := &in.LinkOnly, &out.LinkOnly
		*out = new(bool)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Mappers != nil {
		in, out := &in.Mappers, &out.Mappers
		*out = make([]RealmIdentityProviderMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmIdentityProvider.
func (in *RealmIdentityProvider) DeepCopy() *RealmIdentityProvider {
	if in == nil {
		return nil
	}
	out := new(RealmIdentityProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmIdentityProviderMapper) DeepCopyInto(out *RealmIdentityProviderMapper) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmIdentityProviderMapper.
func (in *RealmIdentityProviderMapper) DeepCopy() *RealmIdentityProviderMapper {
	if in == nil {
		return nil
	}
	out := new(RealmIdentityProviderMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmRole) DeepCopyInto(out *RealmRole) {
	*out = *in
	if in.Composites != nil {
		in, out := &in.Composites, &out.Composites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmRole.
func (in *RealmRole) DeepCopy() *RealmRole {
	if in == nil {
		return nil
	}
	out := new(RealmRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmSecurityProfile) DeepCopyInto(out *RealmSecurityProfile) {
	*out = *in
	if in.PasswordHistory != nil {
		in, out := &in.PasswordHistory, &out.PasswordHistory
		*out = new(int)
		**out = **in
	}
	if in.PasswordRequireUppercase != nil {
		in, out := &in.PasswordRequireUppercase, &out.PasswordRequireUppercase
		*out = new(bool)
		**out = **in
	}
	if in.PasswordRequireLowercase != nil {
		in, out := &in.PasswordRequireLowercase, &out.PasswordRequireLowercase
		*out = new(bool)
		**out = **in
	}
	if in.PasswordRequireDigit != nil {
		in, out := &in.PasswordRequireDigit, &out.PasswordRequireDigit
		*out = new(bool)
		**out = **in
	}
	if in.PasswordRequireSpecial != nil {
		in, out := &in.PasswordRequireSpecial, &out.PasswordRequireSpecial
		*out = new(bool)
		**out = **in
	}
	if in.PasswordDisallowUsername != nil {
		in, out := &in.PasswordDisallowUsername, &out.PasswordDisallowUsername
		*out = new(bool)
		**out = **in
	}
	if in.PasswordDisallowEmail != nil {
		in, out := &in.PasswordDisallowEmail, &out.PasswordDisallowEmail
		*out = new(bool)
		**out = **in
	}
	if in.BruteForce != nil {
		in, out := &in.BruteForce, &out.BruteForce
		*out = new(BruteForcePolicy)
		**out = **in
	}
	if in.EmailVerificationRequired != nil {
		in, out := &in.EmailVerificationRequired, &out.EmailVerificationRequired
		*out = new(bool)
		**out = **in
	}
	if in.RememberMeEnabled != nil {
		in, out := &in.RememberMeEnabled, &out.RememberMeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.UserRegistrationEnabled != nil {
		in, out := &in.UserRegistrationEnabled, &out.UserRegistrationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.UserEventsEnabled != nil {
		in, out := &in.UserEventsEnabled, &out.UserEventsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AdminEventsEnabled != nil {
		in, out := &in.AdminEventsEnabled, &out.AdminEventsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AuditRetentionDays != nil {
		in, out := &in.AuditRetentionDays, &out.AuditRetentionDays
		*out = new(int)
		**out = **in
	}
	if in.AuditExportEnabled != nil {
		in, out := &in.AuditExportEnabled, &out.AuditExportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ClientSecretRotationDays != nil {
		in, out := &in.ClientSecretRotationDays, &out.ClientSecretRotationDays
		*out = new(int)
		**out = **in
	}
	if in.IDPBrokerRequireSignature != nil {
		in, out := &in.IDPBrokerRequireSignature, &out.IDPBrokerRequireSignature
		*out = new(bool)
		**out = **in
	}
	if in.IDPBrokerTrustEmail != nil {
		in, out := &in.IDPBrokerTrustEmail, &out.IDPBrokerTrustEmail
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmSecurityProfile.
func (in *RealmSecurityProfile) DeepCopy() *RealmSecurityProfile {
	if in == nil {
		return nil
	}
	out := new(RealmSecurityProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedMeshServiceEgress) DeepCopyInto(out *ResolvedMeshServiceEgress) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]MeshServicePort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedMeshServiceEgress.
func (in *ResolvedMeshServiceEgress) DeepCopy() *ResolvedMeshServiceEgress {
	if in == nil {
		return nil
	}
	out := new(ResolvedMeshServiceEgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleCapabilitySnapshot) DeepCopyInto(out *RoleCapabilitySnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleCapabilitySnapshot.
func (in *RoleCapabilitySnapshot) DeepCopy() *RoleCapabilitySnapshot {
	if in == nil {
		return nil
	}
	out := new(RoleCapabilitySnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLEndpoints) DeepCopyInto(out *SAMLEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLEndpoints.
func (in *SAMLEndpoints) DeepCopy() *SAMLEndpoints {
	if in == nil {
		return nil
	}
	out := new(SAMLEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
	in.SecretRef.DeepCopyInto(&out.SecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRotationPolicy) DeepCopyInto(out *SecretRotationPolicy) {
	*out = *in
	if in.ForceRotateAt != nil {
		in, out := &in.ForceRotateAt, &out.ForceRotateAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRotationPolicy.
func (in *SecretRotationPolicy) DeepCopy() *SecretRotationPolicy {
	if in == nil {
		return nil
	}
	out := new(SecretRotationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeSpec) DeepCopyInto(out *UpgradeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeSpec.
func (in *UpgradeSpec) DeepCopy() *UpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeSpec)
	in.DeepCopyInto(out)
	return out
}
